### ISSUE TITLE
Key Error : input_text_a when execute train.py

### ISSUE THREAD

**Issue by aaajeong** [NTDXYG/ComFormer#2]
Hello :)
I was impressed with your Comformer thesis so I tried your Comformer code.
As it says in README.md, we made csv file with 2 columns (input_text, target_text).
However, when I run "python train.py", the key error is occured.
--> **Key Error :  input_text_a**

How to resolve it? 
Thank you.

This is error description.

(ym37) gpuadmin@gpuadmin:~/youngmi/ComFormer$ python train.py
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO:simpletransformers.seq2seq.seq2seq_utils: Creating features from dataset file at cache_dir/
Traceback (most recent call last):
  File "/home/gpuadmin/anaconda3/envs/ym37/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'input_text_a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 75, in <module>
    model.train_model(train_df, eval_data=eval_df, Rouge=Rouge)
  File "/home/gpuadmin/youngmi/ComFormer/bart_model.py", line 176, in train_model
    train_dataset = self.load_and_cache_examples(train_data, verbose=verbose)
  File "/home/gpuadmin/youngmi/ComFormer/bart_model.py", line 868, in load_and_cache_examples
    dataset = SimpleSummarizationDataset(encoder_tokenizer, self.args, data, mode)
  File "/home/gpuadmin/youngmi/ComFormer/simpletransformers/seq2seq/seq2seq_utils.py", line 383, in __init__
    data["input_text_a"], data["input_text_b"], data["target_text"]
  File "/home/gpuadmin/anaconda3/envs/ym37/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/gpuadmin/anaconda3/envs/ym37/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'input_text_a'

**Comment by NTDXYG** [comment]
I'm sorry that this has caused you problems and I will address this as soon as possible.

**Comment by NTDXYG** [comment]
The problem has been fixed, the previous error was due to a problem I had when I was trying to modify the pre-training code, it has now been fixed.

**Comment by NTDXYG** [comment]
The dataset used in the thesis can be downloaded at https://github.com/xing-hu/EMSE-DeepCom. Another thing to note is that the dataset was pre-processed; I limited the length of the code and the abstract syntax tree sequence to 256, and truncated the excess and then spliced it. This may not have been mentioned in detail in the paper. Keep leaving comments if you have questions and I'll take care of it.
